# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Upgrade pip
      run: |
        python3 -m pip install --upgrade pip
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        cache: 'true'
        cache-key-prefix: 'qt-cache-lin'
        version: '6.7.3'
        setup-python: false
    - name: Install dependencies
      run: |
        pip3 -v install --config-settings --confirm-license= --no-binary :all: PyQt6
        pip3 install pyinstaller
    - name: Build with pyinstaller
      run: |
        pyinstaller mytest.spec
